version: "3"

services:
  esmsdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: esmsdb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbvol:/var/lib/mysql

  esmsad:
    depends_on:
      - esmsdb
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_HOST: esmsdb:3306
      ADMINER_DEFAULT_DB_NAME: esmsdb
      ADMINER_DESIGN: nette
    ports:
      - "8080:8080"

  # esmsbe:
  #   depends_on:
  #     - esmsdb
  #   build: .
  #   image: esmsbe:devlocal
  #   restart: always
  #   ports:
  #     - "4000:8000"
volumes:
  dbvol:
