on: [push]

name: Deploy_To_Azure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build and push image'
      run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/esmsbe:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/esmsbe:latest

    - name: Logout Azure
      run: |
        az logout
  
